version: '3.8'

services:
  backend:
    build:
      context: ./url_exct_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    build:
      context: ./url_exct_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
